CC=gcc -g -Os
CXX=g++ -g -Os
#CC=gcc -O2
INC=${INCPATH} -I./ -I../ -I../include
CFLAGS= `pkg-config --cflags Qt5Core Qt5Gui Qt5Widgets` -fPIC
CXXFLAGS= ${CFLAGS}

SYSTEM_LIBS = `pkg-config --libs Qt5Core Qt5Gui Qt5Widgets` ${FREETYPE_LIBS} -lpicasso2_sw -lpthread -lstdc++ -lm

objs = main.o callback.o interface.o functions.o popmenu.o

all: agave_browser

agave_browser : ${objs}
	libtool --mode=link ${CC} ${objs} ../src/libagave.la -o $@ ${INC} ${SYSTEM_LIBS}

interface.o : interface.cpp
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

callback.o : callback.cpp
	${CC} ${CFLAGS} -c $< -o $@ ${INC}

functions.o : qt5/functions.cpp
	${CXX} ${CXXFLAGS} -c $< -o $@ ${INC}

popmenu.o : qt5/popmenu.cpp
	${CXX} ${CXXFLAGS} -c $< -o $@ ${INC}

main.o : qt5/main.cpp
	${CXX} ${CXXFLAGS} -c $< -o $@ ${INC}

clean:
	rm *.o *.out agave_browser
