/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf -L ANSI-C -E -C -n -o -t --key-positions='*' -NfindValue -Hhash_val -Wwordlist_value -D CSSValueKeywords.gperf  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "CSSValueKeywords.gperf"

/* This file is automatically generated from CSSValueKeywords.in by makevalues, do not edit */

#include "CSSValueKeywords.h"
#line 6 "CSSValueKeywords.gperf"
struct css_value {
    const char* name;
    int id;
};
/* maximum key range = 2924, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_val (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924,  295,   31, 2924,    0,    0,
       115,   95,   90,   80,   55,   40,   30,   10, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924,  115,   15,   70,
       390,    5,  190,  435,  238,   45,   28,   75,    0,   25,
       150,   15,  145,    1,    5,    0,    5,   35,    3,  308,
        68,   41,  205, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924, 2924,
      2924, 2924, 2924, 2924, 2924, 2924, 2924
    };
  register unsigned int hval = 0;

  switch (len)
    {
      default:
        hval += asso_values[(unsigned char)str[29]];
      /*FALLTHROUGH*/
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      /*FALLTHROUGH*/
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      /*FALLTHROUGH*/
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      /*FALLTHROUGH*/
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      /*FALLTHROUGH*/
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      /*FALLTHROUGH*/
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      /*FALLTHROUGH*/
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      /*FALLTHROUGH*/
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      /*FALLTHROUGH*/
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      /*FALLTHROUGH*/
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      /*FALLTHROUGH*/
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      /*FALLTHROUGH*/
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      /*FALLTHROUGH*/
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      /*FALLTHROUGH*/
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      /*FALLTHROUGH*/
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]+1];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]+1];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

const struct css_value *
findValue (register const char *str, register size_t len)
{
  enum
    {
      TOTAL_KEYWORDS = 371,
      MIN_WORD_LENGTH = 2,
      MAX_WORD_LENGTH = 30,
      MIN_HASH_VALUE = 0,
      MAX_HASH_VALUE = 2923
    };

  static const struct css_value wordlist_value[] =
    {
#line 39 "CSSValueKeywords.gperf"
      {"100", CSS_VAL_100},
#line 235 "CSSValueKeywords.gperf"
      {"ltr", CSS_VAL_LTR},
#line 47 "CSSValueKeywords.gperf"
      {"900", CSS_VAL_900},
#line 86 "CSSValueKeywords.gperf"
      {"red", CSS_VAL_RED},
#line 381 "CSSValueKeywords.gperf"
      {"to", CSS_VAL_TO},
#line 148 "CSSValueKeywords.gperf"
      {"top", CSS_VAL_TOP},
#line 262 "CSSValueKeywords.gperf"
      {"loud", CSS_VAL_LOUD},
#line 286 "CSSValueKeywords.gperf"
      {"start", CSS_VAL_START},
#line 163 "CSSValueKeywords.gperf"
      {"square", CSS_VAL_SQUARE},
#line 46 "CSSValueKeywords.gperf"
      {"800", CSS_VAL_800},
#line 236 "CSSValueKeywords.gperf"
      {"rtl", CSS_VAL_RTL},
#line 303 "CSSValueKeywords.gperf"
      {"slide", CSS_VAL_SLIDE},
#line 45 "CSSValueKeywords.gperf"
      {"700", CSS_VAL_700},
#line 359 "CSSValueKeywords.gperf"
      {"border", CSS_VAL_BORDER},
#line 25 "CSSValueKeywords.gperf"
      {"menu", CSS_VAL_MENU},
#line 88 "CSSValueKeywords.gperf"
      {"teal", CSS_VAL_TEAL},
#line 44 "CSSValueKeywords.gperf"
      {"600", CSS_VAL_600},
#line 36 "CSSValueKeywords.gperf"
      {"bold", CSS_VAL_BOLD},
#line 50 "CSSValueKeywords.gperf"
      {"small", CSS_VAL_SMALL},
#line 37 "CSSValueKeywords.gperf"
      {"bolder", CSS_VAL_BOLDER},
#line 56 "CSSValueKeywords.gperf"
      {"smaller", CSS_VAL_SMALLER},
#line 43 "CSSValueKeywords.gperf"
      {"500", CSS_VAL_500},
#line 139 "CSSValueKeywords.gperf"
      {"xor", CSS_VAL_XOR},
#line 143 "CSSValueKeywords.gperf"
      {"middle", CSS_VAL_MIDDLE},
#line 231 "CSSValueKeywords.gperf"
      {"text", CSS_VAL_TEXT},
#line 367 "CSSValueKeywords.gperf"
      {"row", CSS_VAL_ROW},
#line 42 "CSSValueKeywords.gperf"
      {"400", CSS_VAL_400},
#line 41 "CSSValueKeywords.gperf"
      {"300", CSS_VAL_300},
#line 332 "CSSValueKeywords.gperf"
      {"menulist", CSS_VAL_MENULIST},
#line 312 "CSSValueKeywords.gperf"
      {"clip", CSS_VAL_CLIP},
#line 18 "CSSValueKeywords.gperf"
      {"outset", CSS_VAL_OUTSET},
#line 240 "CSSValueKeywords.gperf"
      {"visible", CSS_VAL_VISIBLE},
#line 144 "CSSValueKeywords.gperf"
      {"sub", CSS_VAL_SUB},
#line 276 "CSSValueKeywords.gperf"
      {"relative", CSS_VAL_RELATIVE},
#line 249 "CSSValueKeywords.gperf"
      {"both", CSS_VAL_BOTH},
#line 265 "CSSValueKeywords.gperf"
      {"mix", CSS_VAL_MIX},
#line 40 "CSSValueKeywords.gperf"
      {"200", CSS_VAL_200},
#line 51 "CSSValueKeywords.gperf"
      {"medium", CSS_VAL_MEDIUM},
#line 33 "CSSValueKeywords.gperf"
      {"oblique", CSS_VAL_OBLIQUE},
#line 209 "CSSValueKeywords.gperf"
      {"cell", CSS_VAL_CELL},
#line 112 "CSSValueKeywords.gperf"
      {"menutext", CSS_VAL_MENUTEXT},
#line 248 "CSSValueKeywords.gperf"
      {"blink", CSS_VAL_BLINK},
#line 74 "CSSValueKeywords.gperf"
      {"aqua", CSS_VAL_AQUA},
#line 154 "CSSValueKeywords.gperf"
      {"center", CSS_VAL_CENTER},
#line 149 "CSSValueKeywords.gperf"
      {"bottom", CSS_VAL_BOTTOM},
#line 368 "CSSValueKeywords.gperf"
      {"row-reverse", CSS_VAL_ROW_REVERSE},
#line 278 "CSSValueKeywords.gperf"
      {"separate", CSS_VAL_SEPARATE},
#line 211 "CSSValueKeywords.gperf"
      {"alias", CSS_VAL_ALIAS},
#line 287 "CSSValueKeywords.gperf"
      {"end", CSS_VAL_END},
#line 70 "CSSValueKeywords.gperf"
      {"cursive", CSS_VAL_CURSIVE},
#line 331 "CSSValueKeywords.gperf"
      {"listitem", CSS_VAL_LISTITEM},
#line 325 "CSSValueKeywords.gperf"
      {"radio", CSS_VAL_RADIO},
#line 280 "CSSValueKeywords.gperf"
      {"static", CSS_VAL_STATIC},
#line 365 "CSSValueKeywords.gperf"
      {"visual", CSS_VAL_VISUAL},
#line 377 "CSSValueKeywords.gperf"
      {"span", CSS_VAL_SPAN},
#line 298 "CSSValueKeywords.gperf"
      {"up", CSS_VAL_UP},
#line 330 "CSSValueKeywords.gperf"
      {"listbox", CSS_VAL_LISTBOX},
#line 85 "CSSValueKeywords.gperf"
      {"purple", CSS_VAL_PURPLE},
#line 32 "CSSValueKeywords.gperf"
      {"italic", CSS_VAL_ITALIC},
#line 76 "CSSValueKeywords.gperf"
      {"blue", CSS_VAL_BLUE},
#line 300 "CSSValueKeywords.gperf"
      {"slow", CSS_VAL_SLOW},
#line 277 "CSSValueKeywords.gperf"
      {"scroll", CSS_VAL_SCROLL},
#line 206 "CSSValueKeywords.gperf"
      {"pointer", CSS_VAL_POINTER},
#line 187 "CSSValueKeywords.gperf"
      {"table", CSS_VAL_TABLE},
#line 251 "CSSValueKeywords.gperf"
      {"crop", CSS_VAL_CROP},
#line 68 "CSSValueKeywords.gperf"
      {"serif", CSS_VAL_SERIF},
#line 252 "CSSValueKeywords.gperf"
      {"cross", CSS_VAL_CROSS},
#line 145 "CSSValueKeywords.gperf"
      {"super", CSS_VAL_SUPER},
#line 244 "CSSValueKeywords.gperf"
      {"always", CSS_VAL_ALWAYS},
#line 313 "CSSValueKeywords.gperf"
      {"ellipsis", CSS_VAL_ELLIPSIS},
#line 366 "CSSValueKeywords.gperf"
      {"lines", CSS_VAL_LINES},
#line 234 "CSSValueKeywords.gperf"
      {"all-scroll", CSS_VAL_ALL_SCROLL},
#line 233 "CSSValueKeywords.gperf"
      {"help", CSS_VAL_HELP},
#line 290 "CSSValueKeywords.gperf"
      {"vertical", CSS_VAL_VERTICAL},
#line 24 "CSSValueKeywords.gperf"
      {"icon", CSS_VAL_ICON},
#line 263 "CSSValueKeywords.gperf"
      {"lower", CSS_VAL_LOWER},
#line 129 "CSSValueKeywords.gperf"
      {"clear", CSS_VAL_CLEAR},
#line 184 "CSSValueKeywords.gperf"
      {"run-in", CSS_VAL_RUN_IN},
#line 328 "CSSValueKeywords.gperf"
      {"button", CSS_VAL_BUTTON},
#line 282 "CSSValueKeywords.gperf"
      {"thin", CSS_VAL_THIN},
#line 369 "CSSValueKeywords.gperf"
      {"column", CSS_VAL_COLUMN},
#line 130 "CSSValueKeywords.gperf"
      {"copy", CSS_VAL_COPY},
#line 360 "CSSValueKeywords.gperf"
      {"content", CSS_VAL_CONTENT},
#line 221 "CSSValueKeywords.gperf"
      {"se-resize", CSS_VAL_SE_RESIZE},
#line 17 "CSSValueKeywords.gperf"
      {"ridge", CSS_VAL_RIDGE},
#line 293 "CSSValueKeywords.gperf"
      {"single", CSS_VAL_SINGLE},
#line 48 "CSSValueKeywords.gperf"
      {"xx-small", CSS_VAL_XX_SMALL},
#line 294 "CSSValueKeywords.gperf"
      {"multiple", CSS_VAL_MULTIPLE},
#line 125 "CSSValueKeywords.gperf"
      {"repeat", CSS_VAL_REPEAT},
#line 243 "CSSValueKeywords.gperf"
      {"absolute", CSS_VAL_ABSOLUTE},
#line 357 "CSSValueKeywords.gperf"
      {"textarea", CSS_VAL_TEXTAREA},
#line 375 "CSSValueKeywords.gperf"
      {"wrap", CSS_VAL_WRAP},
#line 203 "CSSValueKeywords.gperf"
      {"auto", CSS_VAL_AUTO},
#line 153 "CSSValueKeywords.gperf"
      {"right", CSS_VAL_RIGHT},
#line 273 "CSSValueKeywords.gperf"
      {"pre", CSS_VAL_PRE},
#line 38 "CSSValueKeywords.gperf"
      {"lighter", CSS_VAL_LIGHTER},
#line 301 "CSSValueKeywords.gperf"
      {"fast", CSS_VAL_FAST},
#line 113 "CSSValueKeywords.gperf"
      {"scrollbar", CSS_VAL_SCROLLBAR},
#line 83 "CSSValueKeywords.gperf"
      {"olive", CSS_VAL_OLIVE},
#line 52 "CSSValueKeywords.gperf"
      {"large", CSS_VAL_LARGE},
#line 57 "CSSValueKeywords.gperf"
      {"larger", CSS_VAL_LARGER},
#line 270 "CSSValueKeywords.gperf"
      {"overlay", CSS_VAL_OVERLAY},
#line 272 "CSSValueKeywords.gperf"
      {"portrait", CSS_VAL_PORTRAIT},
#line 213 "CSSValueKeywords.gperf"
      {"no-drop", CSS_VAL_NO_DROP},
#line 101 "CSSValueKeywords.gperf"
      {"buttontext", CSS_VAL_BUTTONTEXT},
#line 13 "CSSValueKeywords.gperf"
      {"none", CSS_VAL_NONE},
#line 255 "CSSValueKeywords.gperf"
      {"hand", CSS_VAL_HAND},
#line 155 "CSSValueKeywords.gperf"
      {"justify", CSS_VAL_JUSTIFY},
#line 350 "CSSValueKeywords.gperf"
      {"caret", CSS_VAL_CARET},
#line 230 "CSSValueKeywords.gperf"
      {"row-resize", CSS_VAL_ROW_RESIZE},
#line 80 "CSSValueKeywords.gperf"
      {"lime", CSS_VAL_LIME},
#line 87 "CSSValueKeywords.gperf"
      {"silver", CSS_VAL_SILVER},
#line 15 "CSSValueKeywords.gperf"
      {"inset", CSS_VAL_INSET},
#line 241 "CSSValueKeywords.gperf"
      {"collapse", CSS_VAL_COLLAPSE},
#line 181 "CSSValueKeywords.gperf"
      {"inline", CSS_VAL_INLINE},
#line 229 "CSSValueKeywords.gperf"
      {"col-resize", CSS_VAL_COL_RESIZE},
#line 271 "CSSValueKeywords.gperf"
      {"overline", CSS_VAL_OVERLINE},
#line 318 "CSSValueKeywords.gperf"
      {"continuous", CSS_VAL_CONTINUOUS},
#line 131 "CSSValueKeywords.gperf"
      {"source-over", CSS_VAL_SOURCE_OVER},
#line 12 "CSSValueKeywords.gperf"
      {"initial", CSS_VAL_INITIAL},
#line 90 "CSSValueKeywords.gperf"
      {"yellow", CSS_VAL_YELLOW},
#line 380 "CSSValueKeywords.gperf"
      {"dense", CSS_VAL_DENSE},
#line 199 "CSSValueKeywords.gperf"
      {"flex", CSS_VAL_FLEX},
#line 185 "CSSValueKeywords.gperf"
      {"compact", CSS_VAL_COMPACT},
#line 358 "CSSValueKeywords.gperf"
      {"round", CSS_VAL_ROUND},
#line 35 "CSSValueKeywords.gperf"
      {"normal", CSS_VAL_NORMAL},
#line 23 "CSSValueKeywords.gperf"
      {"caption", CSS_VAL_CAPTION},
#line 362 "CSSValueKeywords.gperf"
      {"border-box", CSS_VAL_BORDER_BOX},
#line 226 "CSSValueKeywords.gperf"
      {"ns-resize", CSS_VAL_NS_RESIZE},
#line 133 "CSSValueKeywords.gperf"
      {"source-out", CSS_VAL_SOURCE_OUT},
#line 218 "CSSValueKeywords.gperf"
      {"ne-resize", CSS_VAL_NE_RESIZE},
#line 14 "CSSValueKeywords.gperf"
      {"hidden", CSS_VAL_HIDDEN},
#line 81 "CSSValueKeywords.gperf"
      {"maroon", CSS_VAL_MAROON},
#line 279 "CSSValueKeywords.gperf"
      {"show", CSS_VAL_SHOW},
#line 21 "CSSValueKeywords.gperf"
      {"solid", CSS_VAL_SOLID},
#line 183 "CSSValueKeywords.gperf"
      {"list-item", CSS_VAL_LIST_ITEM},
#line 147 "CSSValueKeywords.gperf"
      {"text-bottom", CSS_VAL_TEXT_BOTTOM},
#line 91 "CSSValueKeywords.gperf"
      {"transparent", CSS_VAL_TRANSPARENT},
#line 364 "CSSValueKeywords.gperf"
      {"logical", CSS_VAL_LOGICAL},
#line 239 "CSSValueKeywords.gperf"
      {"lowercase", CSS_VAL_LOWERCASE},
#line 259 "CSSValueKeywords.gperf"
      {"landscape", CSS_VAL_LANDSCAPE},
#line 128 "CSSValueKeywords.gperf"
      {"no-repeat", CSS_VAL_NO_REPEAT},
#line 201 "CSSValueKeywords.gperf"
      {"grid", CSS_VAL_GRID},
#line 152 "CSSValueKeywords.gperf"
      {"left", CSS_VAL_LEFT},
#line 334 "CSSValueKeywords.gperf"
      {"menulist-text", CSS_VAL_MENULIST_TEXT},
#line 256 "CSSValueKeywords.gperf"
      {"hide", CSS_VAL_HIDE},
#line 22 "CSSValueKeywords.gperf"
      {"double", CSS_VAL_DOUBLE},
#line 11 "CSSValueKeywords.gperf"
      {"inherit", CSS_VAL_INHERIT},
#line 232 "CSSValueKeywords.gperf"
      {"wait", CSS_VAL_WAIT},
#line 299 "CSSValueKeywords.gperf"
      {"down", CSS_VAL_DOWN},
#line 84 "CSSValueKeywords.gperf"
      {"orange", CSS_VAL_ORANGE},
#line 268 "CSSValueKeywords.gperf"
      {"nowrap", CSS_VAL_NOWRAP},
#line 75 "CSSValueKeywords.gperf"
      {"black", CSS_VAL_BLACK},
#line 246 "CSSValueKeywords.gperf"
      {"below", CSS_VAL_BELOW},
#line 260 "CSSValueKeywords.gperf"
      {"level", CSS_VAL_LEVEL},
#line 308 "CSSValueKeywords.gperf"
      {"element", CSS_VAL_ELEMENT},
#line 285 "CSSValueKeywords.gperf"
      {"stretch", CSS_VAL_STRETCH},
#line 162 "CSSValueKeywords.gperf"
      {"circle", CSS_VAL_CIRCLE},
#line 71 "CSSValueKeywords.gperf"
      {"fantasy", CSS_VAL_FANTASY},
#line 102 "CSSValueKeywords.gperf"
      {"captiontext", CSS_VAL_CAPTIONTEXT},
#line 378 "CSSValueKeywords.gperf"
      {"min-content", CSS_VAL_MIN_CONTENT},
#line 288 "CSSValueKeywords.gperf"
      {"reverse", CSS_VAL_REVERSE},
#line 31 "CSSValueKeywords.gperf"
      {"status-bar", CSS_VAL_STATUS_BAR},
#line 142 "CSSValueKeywords.gperf"
      {"baseline", CSS_VAL_BASELINE},
#line 159 "CSSValueKeywords.gperf"
      {"outside", CSS_VAL_OUTSIDE},
#line 305 "CSSValueKeywords.gperf"
      {"read-only", CSS_VAL_READ_ONLY},
#line 72 "CSSValueKeywords.gperf"
      {"monospace", CSS_VAL_MONOSPACE},
#line 207 "CSSValueKeywords.gperf"
      {"move", CSS_VAL_MOVE},
#line 310 "CSSValueKeywords.gperf"
      {"intrinsic", CSS_VAL_INTRINSIC},
#line 212 "CSSValueKeywords.gperf"
      {"progress", CSS_VAL_PROGRESS},
#line 146 "CSSValueKeywords.gperf"
      {"text-top", CSS_VAL_TEXT_TOP},
#line 327 "CSSValueKeywords.gperf"
      {"square-button", CSS_VAL_SQUARE_BUTTON},
#line 58 "CSSValueKeywords.gperf"
      {"wider", CSS_VAL_WIDER},
#line 322 "CSSValueKeywords.gperf"
      {"space", CSS_VAL_SPACE},
#line 238 "CSSValueKeywords.gperf"
      {"uppercase", CSS_VAL_UPPERCASE},
#line 274 "CSSValueKeywords.gperf"
      {"pre-line", CSS_VAL_PRE_LINE},
#line 257 "CSSValueKeywords.gperf"
      {"higher", CSS_VAL_HIGHER},
#line 250 "CSSValueKeywords.gperf"
      {"close-quote", CSS_VAL_CLOSE_QUOTE},
#line 132 "CSSValueKeywords.gperf"
      {"source-in", CSS_VAL_SOURCE_IN},
#line 283 "CSSValueKeywords.gperf"
      {"underline", CSS_VAL_UNDERLINE},
#line 347 "CSSValueKeywords.gperf"
      {"slider-vertical", CSS_VAL_SLIDER_VERTICAL},
#line 242 "CSSValueKeywords.gperf"
      {"above", CSS_VAL_ABOVE},
#line 237 "CSSValueKeywords.gperf"
      {"capitalize", CSS_VAL_CAPITALIZE},
#line 195 "CSSValueKeywords.gperf"
      {"table-cell", CSS_VAL_TABLE_CELL},
#line 59 "CSSValueKeywords.gperf"
      {"narrower", CSS_VAL_NARROWER},
#line 222 "CSSValueKeywords.gperf"
      {"sw-resize", CSS_VAL_SW_RESIZE},
#line 225 "CSSValueKeywords.gperf"
      {"ew-resize", CSS_VAL_EW_RESIZE},
#line 329 "CSSValueKeywords.gperf"
      {"button-bevel", CSS_VAL_BUTTON_BEVEL},
#line 370 "CSSValueKeywords.gperf"
      {"column-reverse", CSS_VAL_COLUMN_REVERSE},
#line 379 "CSSValueKeywords.gperf"
      {"max-content", CSS_VAL_MAX_CONTENT},
#line 89 "CSSValueKeywords.gperf"
      {"white", CSS_VAL_WHITE},
#line 333 "CSSValueKeywords.gperf"
      {"menulist-button", CSS_VAL_MENULIST_BUTTON},
#line 304 "CSSValueKeywords.gperf"
      {"alternate", CSS_VAL_ALTERNATE},
#line 160 "CSSValueKeywords.gperf"
      {"inside", CSS_VAL_INSIDE},
#line 182 "CSSValueKeywords.gperf"
      {"block", CSS_VAL_BLOCK},
#line 173 "CSSValueKeywords.gperf"
      {"hebrew", CSS_VAL_HEBREW},
#line 204 "CSSValueKeywords.gperf"
      {"crosshair", CSS_VAL_CROSSHAIR},
#line 311 "CSSValueKeywords.gperf"
      {"min-intrinsic", CSS_VAL_MIN_INTRINSIC},
#line 49 "CSSValueKeywords.gperf"
      {"x-small", CSS_VAL_X_SMALL},
#line 309 "CSSValueKeywords.gperf"
      {"ignore", CSS_VAL_IGNORE},
#line 208 "CSSValueKeywords.gperf"
      {"vertical-text", CSS_VAL_VERTICAL_TEXT},
#line 376 "CSSValueKeywords.gperf"
      {"wrap-reverse", CSS_VAL_WRAP_REVERSE},
#line 62 "CSSValueKeywords.gperf"
      {"condensed", CSS_VAL_CONDENSED},
#line 127 "CSSValueKeywords.gperf"
      {"repeat-y", CSS_VAL_REPEAT_Y},
#line 78 "CSSValueKeywords.gperf"
      {"gray", CSS_VAL_GRAY},
#line 98 "CSSValueKeywords.gperf"
      {"buttonface", CSS_VAL_BUTTONFACE},
#line 134 "CSSValueKeywords.gperf"
      {"source-atop", CSS_VAL_SOURCE_ATOP},
#line 69 "CSSValueKeywords.gperf"
      {"sans-serif", CSS_VAL_SANS_SERIF},
#line 253 "CSSValueKeywords.gperf"
      {"embed", CSS_VAL_EMBED},
#line 245 "CSSValueKeywords.gperf"
      {"avoid", CSS_VAL_AVOID},
#line 126 "CSSValueKeywords.gperf"
      {"repeat-x", CSS_VAL_REPEAT_X},
#line 363 "CSSValueKeywords.gperf"
      {"content-box", CSS_VAL_CONTENT_BOX},
#line 34 "CSSValueKeywords.gperf"
      {"small-caps", CSS_VAL_SMALL_CAPS},
#line 94 "CSSValueKeywords.gperf"
      {"activeborder", CSS_VAL_ACTIVEBORDER},
#line 306 "CSSValueKeywords.gperf"
      {"read-write", CSS_VAL_READ_WRITE},
#line 178 "CSSValueKeywords.gperf"
      {"katakana", CSS_VAL_KATAKANA},
#line 119 "CSSValueKeywords.gperf"
      {"window", CSS_VAL_WINDOW},
#line 258 "CSSValueKeywords.gperf"
      {"invert", CSS_VAL_INVERT},
#line 320 "CSSValueKeywords.gperf"
      {"break-all", CSS_VAL_BREAK_ALL},
#line 356 "CSSValueKeywords.gperf"
      {"textfield", CSS_VAL_TEXTFIELD},
#line 269 "CSSValueKeywords.gperf"
      {"open-quote", CSS_VAL_OPEN_QUOTE},
#line 210 "CSSValueKeywords.gperf"
      {"context-menu", CSS_VAL_CONTEXT_MENU},
#line 281 "CSSValueKeywords.gperf"
      {"thick", CSS_VAL_THICK},
#line 16 "CSSValueKeywords.gperf"
      {"groove", CSS_VAL_GROOVE},
#line 223 "CSSValueKeywords.gperf"
      {"s-resize", CSS_VAL_S_RESIZE},
#line 103 "CSSValueKeywords.gperf"
      {"graytext", CSS_VAL_GRAYTEXT},
#line 217 "CSSValueKeywords.gperf"
      {"e-resize", CSS_VAL_E_RESIZE},
#line 219 "CSSValueKeywords.gperf"
      {"nw-resize", CSS_VAL_NW_RESIZE},
#line 326 "CSSValueKeywords.gperf"
      {"push-button", CSS_VAL_PUSH_BUTTON},
#line 54 "CSSValueKeywords.gperf"
      {"xx-large", CSS_VAL_XX_LARGE},
#line 96 "CSSValueKeywords.gperf"
      {"appworkspace", CSS_VAL_APPWORKSPACE},
#line 289 "CSSValueKeywords.gperf"
      {"horizontal", CSS_VAL_HORIZONTAL},
#line 82 "CSSValueKeywords.gperf"
      {"navy", CSS_VAL_NAVY},
#line 121 "CSSValueKeywords.gperf"
      {"windowtext", CSS_VAL_WINDOWTEXT},
#line 295 "CSSValueKeywords.gperf"
      {"forwards", CSS_VAL_FORWARDS},
#line 227 "CSSValueKeywords.gperf"
      {"nesw-resize", CSS_VAL_NESW_RESIZE},
#line 95 "CSSValueKeywords.gperf"
      {"activecaption", CSS_VAL_ACTIVECAPTION},
#line 111 "CSSValueKeywords.gperf"
      {"match", CSS_VAL_MATCH},
#line 194 "CSSValueKeywords.gperf"
      {"table-column", CSS_VAL_TABLE_COLUMN},
#line 77 "CSSValueKeywords.gperf"
      {"fuchsia", CSS_VAL_FUCHSIA},
#line 161 "CSSValueKeywords.gperf"
      {"disc", CSS_VAL_DISC},
#line 123 "CSSValueKeywords.gperf"
      {"grey", CSS_VAL_GREY},
#line 188 "CSSValueKeywords.gperf"
      {"inline-table", CSS_VAL_INLINE_TABLE},
#line 192 "CSSValueKeywords.gperf"
      {"table-row", CSS_VAL_TABLE_ROW},
#line 371 "CSSValueKeywords.gperf"
      {"flex-start", CSS_VAL_FLEX_START},
#line 53 "CSSValueKeywords.gperf"
      {"x-large", CSS_VAL_X_LARGE},
#line 254 "CSSValueKeywords.gperf"
      {"fixed", CSS_VAL_FIXED},
#line 110 "CSSValueKeywords.gperf"
      {"infotext", CSS_VAL_INFOTEXT},
#line 247 "CSSValueKeywords.gperf"
      {"bidi-override", CSS_VAL_BIDI_OVERRIDE},
#line 302 "CSSValueKeywords.gperf"
      {"infinite", CSS_VAL_INFINITE},
#line 19 "CSSValueKeywords.gperf"
      {"dotted", CSS_VAL_DOTTED},
#line 186 "CSSValueKeywords.gperf"
      {"inline-block", CSS_VAL_INLINE_BLOCK},
#line 166 "CSSValueKeywords.gperf"
      {"lower-roman", CSS_VAL_LOWER_ROMAN},
#line 205 "CSSValueKeywords.gperf"
      {"default", CSS_VAL_DEFAULT},
#line 170 "CSSValueKeywords.gperf"
      {"lower-latin", CSS_VAL_LOWER_LATIN},
#line 220 "CSSValueKeywords.gperf"
      {"n-resize", CSS_VAL_N_RESIZE},
#line 361 "CSSValueKeywords.gperf"
      {"padding", CSS_VAL_PADDING},
#line 349 "CSSValueKeywords.gperf"
      {"sliderthumb-vertical", CSS_VAL_SLIDERTHUMB_VERTICAL},
#line 27 "CSSValueKeywords.gperf"
      {"small-caption", CSS_VAL_SMALL_CAPTION},
#line 174 "CSSValueKeywords.gperf"
      {"armenian", CSS_VAL_ARMENIAN},
#line 317 "CSSValueKeywords.gperf"
      {"wave", CSS_VAL_WAVE},
#line 291 "CSSValueKeywords.gperf"
      {"inline-axis", CSS_VAL_INLINE_AXIS},
#line 275 "CSSValueKeywords.gperf"
      {"pre-wrap", CSS_VAL_PRE_WRAP},
#line 297 "CSSValueKeywords.gperf"
      {"ahead", CSS_VAL_AHEAD},
#line 20 "CSSValueKeywords.gperf"
      {"dashed", CSS_VAL_DASHED},
#line 164 "CSSValueKeywords.gperf"
      {"decimal", CSS_VAL_DECIMAL},
#line 351 "CSSValueKeywords.gperf"
      {"searchfield", CSS_VAL_SEARCHFIELD},
#line 200 "CSSValueKeywords.gperf"
      {"inline-flex", CSS_VAL_INLINE_FLEX},
#line 266 "CSSValueKeywords.gperf"
      {"no-close-quote", CSS_VAL_NO_CLOSE_QUOTE},
#line 79 "CSSValueKeywords.gperf"
      {"green", CSS_VAL_GREEN},
#line 167 "CSSValueKeywords.gperf"
      {"upper-roman", CSS_VAL_UPPER_ROMAN},
#line 172 "CSSValueKeywords.gperf"
      {"upper-latin", CSS_VAL_UPPER_LATIN},
#line 26 "CSSValueKeywords.gperf"
      {"message-box", CSS_VAL_MESSAGE_BOX},
#line 267 "CSSValueKeywords.gperf"
      {"no-open-quote", CSS_VAL_NO_OPEN_QUOTE},
#line 65 "CSSValueKeywords.gperf"
      {"expanded", CSS_VAL_EXPANDED},
#line 120 "CSSValueKeywords.gperf"
      {"windowframe", CSS_VAL_WINDOWFRAME},
#line 140 "CSSValueKeywords.gperf"
      {"plus-darker", CSS_VAL_PLUS_DARKER},
#line 224 "CSSValueKeywords.gperf"
      {"w-resize", CSS_VAL_W_RESIZE},
#line 336 "CSSValueKeywords.gperf"
      {"scrollbarbutton-up", CSS_VAL_SCROLLBARBUTTON_UP},
#line 196 "CSSValueKeywords.gperf"
      {"table-caption", CSS_VAL_TABLE_CAPTION},
#line 324 "CSSValueKeywords.gperf"
      {"checkbox", CSS_VAL_CHECKBOX},
#line 214 "CSSValueKeywords.gperf"
      {"not-allowed", CSS_VAL_NOT_ALLOWED},
#line 338 "CSSValueKeywords.gperf"
      {"scrollbarbutton-left", CSS_VAL_SCROLLBARBUTTON_LEFT},
#line 106 "CSSValueKeywords.gperf"
      {"inactiveborder", CSS_VAL_INACTIVEBORDER},
#line 168 "CSSValueKeywords.gperf"
      {"lower-greek", CSS_VAL_LOWER_GREEK},
#line 335 "CSSValueKeywords.gperf"
      {"menulist-textfield", CSS_VAL_MENULIST_TEXTFIELD},
#line 177 "CSSValueKeywords.gperf"
      {"hiragana", CSS_VAL_HIRAGANA},
#line 346 "CSSValueKeywords.gperf"
      {"slider-horizontal", CSS_VAL_SLIDER_HORIZONTAL},
#line 292 "CSSValueKeywords.gperf"
      {"block-axis", CSS_VAL_BLOCK_AXIS},
#line 341 "CSSValueKeywords.gperf"
      {"scrollbartrack-vertical", CSS_VAL_SCROLLBARTRACK_VERTICAL},
#line 141 "CSSValueKeywords.gperf"
      {"plus-lighter", CSS_VAL_PLUS_LIGHTER},
#line 169 "CSSValueKeywords.gperf"
      {"lower-alpha", CSS_VAL_LOWER_ALPHA},
#line 107 "CSSValueKeywords.gperf"
      {"inactivecaption", CSS_VAL_INACTIVECAPTION},
#line 115 "CSSValueKeywords.gperf"
      {"threedface", CSS_VAL_THREEDFACE},
#line 343 "CSSValueKeywords.gperf"
      {"scrollbarthumb-vertical", CSS_VAL_SCROLLBARTHUMB_VERTICAL},
#line 228 "CSSValueKeywords.gperf"
      {"nwse-resize", CSS_VAL_NWSE_RESIZE},
#line 315 "CSSValueKeywords.gperf"
      {"dot-dash", CSS_VAL_DOT_DASH},
#line 372 "CSSValueKeywords.gperf"
      {"flex-end", CSS_VAL_FLEX_END},
#line 135 "CSSValueKeywords.gperf"
      {"destination-over", CSS_VAL_DESTINATION_OVER},
#line 171 "CSSValueKeywords.gperf"
      {"upper-alpha", CSS_VAL_UPPER_ALPHA},
#line 108 "CSSValueKeywords.gperf"
      {"inactivecaptiontext", CSS_VAL_INACTIVECAPTIONTEXT},
#line 104 "CSSValueKeywords.gperf"
      {"highlight", CSS_VAL_HIGHLIGHT},
#line 137 "CSSValueKeywords.gperf"
      {"destination-out", CSS_VAL_DESTINATION_OUT},
#line 321 "CSSValueKeywords.gperf"
      {"break-word", CSS_VAL_BREAK_WORD},
#line 175 "CSSValueKeywords.gperf"
      {"georgian", CSS_VAL_GEORGIAN},
#line 296 "CSSValueKeywords.gperf"
      {"backwards", CSS_VAL_BACKWARDS},
#line 314 "CSSValueKeywords.gperf"
      {"discard", CSS_VAL_DISCARD},
#line 373 "CSSValueKeywords.gperf"
      {"space-between", CSS_VAL_SPACE_BETWEEN},
#line 100 "CSSValueKeywords.gperf"
      {"buttonshadow", CSS_VAL_BUTTONSHADOW},
#line 124 "CSSValueKeywords.gperf"
      {"-webkit-text", CSS_VAL__WEBKIT_TEXT},
#line 105 "CSSValueKeywords.gperf"
      {"highlighttext", CSS_VAL_HIGHLIGHTTEXT},
#line 197 "CSSValueKeywords.gperf"
      {"-webkit-box", CSS_VAL__WEBKIT_BOX},
#line 180 "CSSValueKeywords.gperf"
      {"katakana-iroha", CSS_VAL_KATAKANA_IROHA},
#line 348 "CSSValueKeywords.gperf"
      {"sliderthumb-horizontal", CSS_VAL_SLIDERTHUMB_HORIZONTAL},
#line 136 "CSSValueKeywords.gperf"
      {"destination-in", CSS_VAL_DESTINATION_IN},
#line 151 "CSSValueKeywords.gperf"
      {"-webkit-auto", CSS_VAL__WEBKIT_AUTO},
#line 264 "CSSValueKeywords.gperf"
      {"-webkit-marquee", CSS_VAL__WEBKIT_MARQUEE},
#line 156 "CSSValueKeywords.gperf"
      {"-webkit-left", CSS_VAL__WEBKIT_LEFT},
#line 261 "CSSValueKeywords.gperf"
      {"line-through", CSS_VAL_LINE_THROUGH},
#line 158 "CSSValueKeywords.gperf"
      {"-webkit-center", CSS_VAL__WEBKIT_CENTER},
#line 138 "CSSValueKeywords.gperf"
      {"destination-atop", CSS_VAL_DESTINATION_ATOP},
#line 30 "CSSValueKeywords.gperf"
      {"-webkit-control", CSS_VAL__WEBKIT_CONTROL},
#line 97 "CSSValueKeywords.gperf"
      {"background", CSS_VAL_BACKGROUND},
#line 92 "CSSValueKeywords.gperf"
      {"-webkit-link", CSS_VAL__WEBKIT_LINK},
#line 374 "CSSValueKeywords.gperf"
      {"space-around", CSS_VAL_SPACE_AROUND},
#line 202 "CSSValueKeywords.gperf"
      {"inline-grid", CSS_VAL_INLINE_GRID},
#line 339 "CSSValueKeywords.gperf"
      {"scrollbarbutton-right", CSS_VAL_SCROLLBARBUTTON_RIGHT},
#line 319 "CSSValueKeywords.gperf"
      {"skip-white-space", CSS_VAL_SKIP_WHITE_SPACE},
#line 176 "CSSValueKeywords.gperf"
      {"cjk-ideographic", CSS_VAL_CJK_IDEOGRAPHIC},
#line 63 "CSSValueKeywords.gperf"
      {"semi-condensed", CSS_VAL_SEMI_CONDENSED},
#line 60 "CSSValueKeywords.gperf"
      {"ultra-condensed", CSS_VAL_ULTRA_CONDENSED},
#line 345 "CSSValueKeywords.gperf"
      {"scrollbargripper-vertical", CSS_VAL_SCROLLBARGRIPPER_VERTICAL},
#line 191 "CSSValueKeywords.gperf"
      {"table-footer-group", CSS_VAL_TABLE_FOOTER_GROUP},
#line 61 "CSSValueKeywords.gperf"
      {"extra-condensed", CSS_VAL_EXTRA_CONDENSED},
#line 340 "CSSValueKeywords.gperf"
      {"scrollbartrack-horizontal", CSS_VAL_SCROLLBARTRACK_HORIZONTAL},
#line 337 "CSSValueKeywords.gperf"
      {"scrollbarbutton-down", CSS_VAL_SCROLLBARBUTTON_DOWN},
#line 193 "CSSValueKeywords.gperf"
      {"table-column-group", CSS_VAL_TABLE_COLUMN_GROUP},
#line 73 "CSSValueKeywords.gperf"
      {"-webkit-body", CSS_VAL__WEBKIT_BODY},
#line 64 "CSSValueKeywords.gperf"
      {"semi-expanded", CSS_VAL_SEMI_EXPANDED},
#line 67 "CSSValueKeywords.gperf"
      {"ultra-expanded", CSS_VAL_ULTRA_EXPANDED},
#line 342 "CSSValueKeywords.gperf"
      {"scrollbarthumb-horizontal", CSS_VAL_SCROLLBARTHUMB_HORIZONTAL},
#line 189 "CSSValueKeywords.gperf"
      {"table-row-group", CSS_VAL_TABLE_ROW_GROUP},
#line 66 "CSSValueKeywords.gperf"
      {"extra-expanded", CSS_VAL_EXTRA_EXPANDED},
#line 93 "CSSValueKeywords.gperf"
      {"-webkit-activelink", CSS_VAL__WEBKIT_ACTIVELINK},
#line 354 "CSSValueKeywords.gperf"
      {"searchfield-results-button", CSS_VAL_SEARCHFIELD_RESULTS_BUTTON},
#line 179 "CSSValueKeywords.gperf"
      {"hiragana-iroha", CSS_VAL_HIRAGANA_IROHA},
#line 216 "CSSValueKeywords.gperf"
      {"-webkit-zoom-out", CSS_VAL__WEBKIT_ZOOM_OUT},
#line 118 "CSSValueKeywords.gperf"
      {"threedshadow", CSS_VAL_THREEDSHADOW},
#line 316 "CSSValueKeywords.gperf"
      {"dot-dot-dash", CSS_VAL_DOT_DOT_DASH},
#line 99 "CSSValueKeywords.gperf"
      {"buttonhighlight", CSS_VAL_BUTTONHIGHLIGHT},
#line 29 "CSSValueKeywords.gperf"
      {"-webkit-small-control", CSS_VAL__WEBKIT_SMALL_CONTROL},
#line 157 "CSSValueKeywords.gperf"
      {"-webkit-right", CSS_VAL__WEBKIT_RIGHT},
#line 284 "CSSValueKeywords.gperf"
      {"-webkit-nowrap", CSS_VAL__WEBKIT_NOWRAP},
#line 307 "CSSValueKeywords.gperf"
      {"read-write-plaintext-only", CSS_VAL_READ_WRITE_PLAINTEXT_ONLY},
#line 215 "CSSValueKeywords.gperf"
      {"-webkit-zoom-in", CSS_VAL__WEBKIT_ZOOM_IN},
#line 323 "CSSValueKeywords.gperf"
      {"after-white-space", CSS_VAL_AFTER_WHITE_SPACE},
#line 352 "CSSValueKeywords.gperf"
      {"searchfield-decoration", CSS_VAL_SEARCHFIELD_DECORATION},
#line 198 "CSSValueKeywords.gperf"
      {"-webkit-inline-box", CSS_VAL__WEBKIT_INLINE_BOX},
#line 109 "CSSValueKeywords.gperf"
      {"infobackground", CSS_VAL_INFOBACKGROUND},
#line 28 "CSSValueKeywords.gperf"
      {"-webkit-mini-control", CSS_VAL__WEBKIT_MINI_CONTROL},
#line 355 "CSSValueKeywords.gperf"
      {"searchfield-cancel-button", CSS_VAL_SEARCHFIELD_CANCEL_BUTTON},
#line 190 "CSSValueKeywords.gperf"
      {"table-header-group", CSS_VAL_TABLE_HEADER_GROUP},
#line 344 "CSSValueKeywords.gperf"
      {"scrollbargripper-horizontal", CSS_VAL_SCROLLBARGRIPPER_HORIZONTAL},
#line 55 "CSSValueKeywords.gperf"
      {"-webkit-xxx-large", CSS_VAL__WEBKIT_XXX_LARGE},
#line 353 "CSSValueKeywords.gperf"
      {"searchfield-results-decoration", CSS_VAL_SEARCHFIELD_RESULTS_DECORATION},
#line 114 "CSSValueKeywords.gperf"
      {"threeddarkshadow", CSS_VAL_THREEDDARKSHADOW},
#line 116 "CSSValueKeywords.gperf"
      {"threedhighlight", CSS_VAL_THREEDHIGHLIGHT},
#line 117 "CSSValueKeywords.gperf"
      {"threedlightshadow", CSS_VAL_THREEDLIGHTSHADOW},
#line 150 "CSSValueKeywords.gperf"
      {"-webkit-baseline-middle", CSS_VAL__WEBKIT_BASELINE_MIDDLE},
#line 165 "CSSValueKeywords.gperf"
      {"decimal-leading-zero", CSS_VAL_DECIMAL_LEADING_ZERO},
#line 122 "CSSValueKeywords.gperf"
      {"-webkit-focus-ring-color", CSS_VAL__WEBKIT_FOCUS_RING_COLOR}
    };

  static const short lookup[] =
    {
        0,  -1,  -1,  -1,  -1,   1,  -1,  -1,  -1,  -1,
        2,  -1,  -1,  -1,  -1,   3,  -1,  -1,  -1,  -1,
        4,   5,  -1,   6,  -1,   7,  -1,  -1,  -1,   8,
        9,  -1,  -1,  -1,  -1,  10,  -1,  -1,  11,  -1,
       12,  -1,  -1,  -1,  -1,  13,  -1,  -1,  14,  -1,
       15,  -1,  -1,  -1,  -1,  16,  -1,  -1,  -1,  -1,
       17,  -1,  -1,  -1,  -1,  18,  -1,  -1,  -1,  -1,
       19,  -1,  -1,  -1,  -1,  20,  -1,  -1,  -1,  -1,
       21,  -1,  -1,  22,  -1,  23,  24,  -1,  25,  -1,
       26,  -1,  -1,  -1,  -1,  27,  -1,  -1,  28,  29,
       30,  31,  -1,  -1,  -1,  32,  -1,  -1,  33,  -1,
       34,  35,  -1,  -1,  -1,  36,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  37,  38,  39,  -1,  -1,  -1,  -1,
       -1,  40,  -1,  41,  42,  43,  -1,  -1,  -1,  -1,
       44,  -1,  -1,  -1,  -1,  -1,  -1,  45,  -1,  -1,
       -1,  46,  -1,  -1,  -1,  -1,  -1,  -1,  47,  -1,
       48,  -1,  -1,  49,  -1,  50,  -1,  -1,  51,  -1,
       52,  53,  -1,  -1,  -1,  54,  -1,  -1,  -1,  -1,
       55,  -1,  -1,  56,  -1,  -1,  57,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  58,  -1,  -1,  59,  -1,
       -1,  -1,  -1,  60,  -1,  61,  -1,  -1,  62,  -1,
       63,  64,  -1,  65,  -1,  66,  -1,  -1,  -1,  -1,
       -1,  67,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  68,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  69,  -1,
       70,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  72,
       -1,  -1,  -1,  73,  -1,  74,  -1,  -1,  75,  -1,
       76,  77,  -1,  -1,  -1,  78,  79,  -1,  80,  -1,
       -1,  81,  -1,  -1,  -1,  82,  83,  -1,  84,  -1,
       -1,  -1,  -1,  85,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  86,  -1,  -1,  87,  -1,  -1,  -1,  -1,
       -1,  88,  -1,  -1,  -1,  89,  90,  -1,  -1,  91,
       92,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  93,  -1,
       94,  -1,  -1,  95,  -1,  96,  -1,  -1,  -1,  -1,
       97,  -1,  -1,  -1,  -1,  -1,  98,  -1,  99,  -1,
       -1,  -1,  -1, 100, 101, 102, 103,  -1, 104,  -1,
      105,  -1,  -1, 106,  -1,  -1,  -1,  -1,  -1, 107,
      108,  -1,  -1,  -1, 109, 110,  -1,  -1, 111,  -1,
       -1,  -1,  -1,  -1,  -1, 112,  -1,  -1,  -1,  -1,
      113,  -1,  -1, 114,  -1,  -1, 115,  -1, 116,  -1,
       -1,  -1,  -1,  -1,  -1, 117, 118,  -1, 119, 120,
      121, 122,  -1,  -1,  -1,  -1, 123,  -1, 124,  -1,
      125, 126,  -1,  -1,  -1,  -1,  -1,  -1, 127,  -1,
       -1, 128,  -1, 129,  -1,  -1, 130,  -1, 131,  -1,
      132, 133,  -1,  -1,  -1,  -1,  -1,  -1, 134,  -1,
      135, 136,  -1,  -1,  -1, 137, 138,  -1, 139,  -1,
      140, 141,  -1, 142,  -1, 143, 144,  -1, 145,  -1,
       -1,  -1,  -1, 146,  -1, 147, 148,  -1, 149,  -1,
      150,  -1,  -1, 151,  -1, 152,  -1,  -1, 153,  -1,
       -1,  -1,  -1, 154,  -1, 155,  -1,  -1, 156,  -1,
      157, 158,  -1,  -1, 159,  -1, 160,  -1, 161,  -1,
      162,  -1,  -1,  -1,  -1, 163,  -1,  -1,  -1,  -1,
      164, 165,  -1,  -1,  -1, 166,  -1,  -1, 167,  -1,
      168,  -1,  -1, 169,  -1,  -1, 170,  -1,  -1, 171,
       -1,  -1,  -1, 172,  -1, 173,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 174,  -1,  -1,  -1,
       -1, 175,  -1,  -1,  -1,  -1, 176,  -1,  -1,  -1,
       -1, 177,  -1, 178,  -1, 179, 180,  -1, 181, 182,
      183,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 184, 185,
       -1,  -1,  -1,  -1, 186,  -1,  -1,  -1, 187,  -1,
       -1, 188, 189,  -1, 190,  -1,  -1,  -1, 191,  -1,
      192,  -1,  -1, 193,  -1, 194, 195,  -1, 196,  -1,
       -1, 197,  -1, 198,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      199, 200, 201,  -1,  -1, 202,  -1, 203,  -1,  -1,
      204,  -1,  -1,  -1,  -1, 205,  -1,  -1, 206,  -1,
       -1,  -1,  -1,  -1,  -1, 207,  -1,  -1,  -1,  -1,
      208, 209,  -1,  -1, 210,  -1,  -1,  -1, 211,  -1,
      212, 213,  -1, 214,  -1, 215, 216,  -1,  -1,  -1,
       -1,  -1,  -1, 217,  -1,  -1,  -1,  -1,  -1,  -1,
      218,  -1,  -1,  -1,  -1,  -1, 219,  -1,  -1,  -1,
       -1, 220,  -1, 221,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 222,  -1, 223,  -1,
      224,  -1,  -1, 225,  -1, 226,  -1,  -1,  -1, 227,
      228,  -1, 229,  -1,  -1,  -1,  -1,  -1,  -1, 230,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 231,  -1,  -1,  -1,  -1,  -1,  -1, 232, 233,
       -1,  -1,  -1, 234,  -1,  -1,  -1,  -1, 235,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 236,  -1, 237,  -1,  -1,  -1,  -1,  -1,  -1,
      238,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      239,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      240,  -1,  -1,  -1,  -1, 241,  -1,  -1, 242,  -1,
       -1,  -1,  -1, 243,  -1,  -1, 244,  -1, 245,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 246,  -1, 247,  -1,
       -1, 248,  -1, 249,  -1,  -1,  -1,  -1,  -1,  -1,
      250,  -1,  -1, 251,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 252,  -1, 253,  -1,  -1, 254,  -1,
      255,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      256,  -1,  -1,  -1, 257, 258,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      259, 260,  -1,  -1,  -1,  -1, 261,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 262,  -1,  -1,  -1, 263,  -1,
      264,  -1,  -1, 265,  -1,  -1,  -1,  -1, 266,  -1,
       -1, 267, 268,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      269,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 270,  -1,  -1,  -1,  -1, 271,  -1, 272,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 273,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 274,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 275,  -1,  -1,  -1,
       -1,  -1,  -1, 276,  -1,  -1,  -1,  -1, 277,  -1,
      278,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      279, 280,  -1,  -1, 281,  -1,  -1,  -1,  -1,  -1,
      282,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 283,  -1,  -1,  -1,  -1, 284,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 285,  -1,  -1,  -1,
       -1,  -1,  -1, 286,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 287,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 288,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 289,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 290,  -1,  -1,  -1,  -1, 291,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 292,  -1,  -1,  -1,  -1, 293,  -1,
       -1, 294,  -1, 295, 296,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 297,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 298, 299,  -1, 300,  -1,  -1, 301,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      302,  -1,  -1, 303,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      304,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 305,  -1,
      306,  -1,  -1, 307,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 308,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 309,  -1,  -1,  -1,
       -1,  -1, 310,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 311,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 312,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 313,
      314,  -1,  -1, 315,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 316,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 317,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 318,  -1,  -1,  -1,
       -1,  -1,  -1, 319,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 320,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 321,  -1,  -1,  -1,  -1,  -1,  -1,
      322,  -1,  -1, 323,  -1,  -1,  -1,  -1,  -1,  -1,
      324,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 325,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 326,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      327,  -1,  -1,  -1,  -1,  -1,  -1, 328,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 329,  -1, 330,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 331,  -1,
      332,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 333,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 334,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 335,  -1,  -1,  -1,  -1,  -1,  -1,
      336,  -1,  -1,  -1, 337,  -1, 338,  -1, 339,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 340,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 341,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 342,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 343,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 344,  -1,  -1, 345,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 346, 347,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 348,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 349,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 350,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 351,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 352,  -1,  -1,  -1,  -1,  -1, 353,  -1,  -1,
       -1,  -1,  -1, 354,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 355,  -1,  -1,  -1,  -1,  -1,  -1, 356,  -1,
       -1, 357,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      358,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 359,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 360,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 361,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 362,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 363,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 364,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 365,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 366,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 367,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 368,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 369,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 370
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash_val (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist_value[index].name;

              if (*str == *s && !strcmp (str + 1, s + 1))
                return &wordlist_value[index];
            }
        }
    }
  return 0;
}
#line 382 "CSSValueKeywords.gperf"

static const char * const valueList[] = {
"",
"inherit", 
"initial", 
"none", 
"hidden", 
"inset", 
"groove", 
"ridge", 
"outset", 
"dotted", 
"dashed", 
"solid", 
"double", 
"caption", 
"icon", 
"menu", 
"message-box", 
"small-caption", 
"-webkit-mini-control", 
"-webkit-small-control", 
"-webkit-control", 
"status-bar", 
"italic", 
"oblique", 
"small-caps", 
"normal", 
"bold", 
"bolder", 
"lighter", 
"100", 
"200", 
"300", 
"400", 
"500", 
"600", 
"700", 
"800", 
"900", 
"xx-small", 
"x-small", 
"small", 
"medium", 
"large", 
"x-large", 
"xx-large", 
"-webkit-xxx-large", 
"smaller", 
"larger", 
"wider", 
"narrower", 
"ultra-condensed", 
"extra-condensed", 
"condensed", 
"semi-condensed", 
"semi-expanded", 
"expanded", 
"extra-expanded", 
"ultra-expanded", 
"serif", 
"sans-serif", 
"cursive", 
"fantasy", 
"monospace", 
"-webkit-body", 
"aqua", 
"black", 
"blue", 
"fuchsia", 
"gray", 
"green", 
"lime", 
"maroon", 
"navy", 
"olive", 
"orange", 
"purple", 
"red", 
"silver", 
"teal", 
"white", 
"yellow", 
"transparent", 
"-webkit-link", 
"-webkit-activelink", 
"activeborder", 
"activecaption", 
"appworkspace", 
"background", 
"buttonface", 
"buttonhighlight", 
"buttonshadow", 
"buttontext", 
"captiontext", 
"graytext", 
"highlight", 
"highlighttext", 
"inactiveborder", 
"inactivecaption", 
"inactivecaptiontext", 
"infobackground", 
"infotext", 
"match", 
"menutext", 
"scrollbar", 
"threeddarkshadow", 
"threedface", 
"threedhighlight", 
"threedlightshadow", 
"threedshadow", 
"window", 
"windowframe", 
"windowtext", 
"-webkit-focus-ring-color", 
"grey", 
"-webkit-text", 
"repeat", 
"repeat-x", 
"repeat-y", 
"no-repeat", 
"clear", 
"copy", 
"source-over", 
"source-in", 
"source-out", 
"source-atop", 
"destination-over", 
"destination-in", 
"destination-out", 
"destination-atop", 
"xor", 
"plus-darker", 
"plus-lighter", 
"baseline", 
"middle", 
"sub", 
"super", 
"text-top", 
"text-bottom", 
"top", 
"bottom", 
"-webkit-baseline-middle", 
"-webkit-auto", 
"left", 
"right", 
"center", 
"justify", 
"-webkit-left", 
"-webkit-right", 
"-webkit-center", 
"outside", 
"inside", 
"disc", 
"circle", 
"square", 
"decimal", 
"decimal-leading-zero", 
"lower-roman", 
"upper-roman", 
"lower-greek", 
"lower-alpha", 
"lower-latin", 
"upper-alpha", 
"upper-latin", 
"hebrew", 
"armenian", 
"georgian", 
"cjk-ideographic", 
"hiragana", 
"katakana", 
"hiragana-iroha", 
"katakana-iroha", 
"inline", 
"block", 
"list-item", 
"run-in", 
"compact", 
"inline-block", 
"table", 
"inline-table", 
"table-row-group", 
"table-header-group", 
"table-footer-group", 
"table-row", 
"table-column-group", 
"table-column", 
"table-cell", 
"table-caption", 
"-webkit-box", 
"-webkit-inline-box", 
"flex", 
"inline-flex", 
"grid", 
"inline-grid", 
"auto", 
"crosshair", 
"default", 
"pointer", 
"move", 
"vertical-text", 
"cell", 
"context-menu", 
"alias", 
"progress", 
"no-drop", 
"not-allowed", 
"-webkit-zoom-in", 
"-webkit-zoom-out", 
"e-resize", 
"ne-resize", 
"nw-resize", 
"n-resize", 
"se-resize", 
"sw-resize", 
"s-resize", 
"w-resize", 
"ew-resize", 
"ns-resize", 
"nesw-resize", 
"nwse-resize", 
"col-resize", 
"row-resize", 
"text", 
"wait", 
"help", 
"all-scroll", 
"ltr", 
"rtl", 
"capitalize", 
"uppercase", 
"lowercase", 
"visible", 
"collapse", 
"above", 
"absolute", 
"always", 
"avoid", 
"below", 
"bidi-override", 
"blink", 
"both", 
"close-quote", 
"crop", 
"cross", 
"embed", 
"fixed", 
"hand", 
"hide", 
"higher", 
"invert", 
"landscape", 
"level", 
"line-through", 
"loud", 
"lower", 
"-webkit-marquee", 
"mix", 
"no-close-quote", 
"no-open-quote", 
"nowrap", 
"open-quote", 
"overlay", 
"overline", 
"portrait", 
"pre", 
"pre-line", 
"pre-wrap", 
"relative", 
"scroll", 
"separate", 
"show", 
"static", 
"thick", 
"thin", 
"underline", 
"-webkit-nowrap", 
"stretch", 
"start", 
"end", 
"reverse", 
"horizontal", 
"vertical", 
"inline-axis", 
"block-axis", 
"single", 
"multiple", 
"forwards", 
"backwards", 
"ahead", 
"up", 
"down", 
"slow", 
"fast", 
"infinite", 
"slide", 
"alternate", 
"read-only", 
"read-write", 
"read-write-plaintext-only", 
"element", 
"ignore", 
"intrinsic", 
"min-intrinsic", 
"clip", 
"ellipsis", 
"discard", 
"dot-dash", 
"dot-dot-dash", 
"wave", 
"continuous", 
"skip-white-space", 
"break-all", 
"break-word", 
"space", 
"after-white-space", 
"checkbox", 
"radio", 
"push-button", 
"square-button", 
"button", 
"button-bevel", 
"listbox", 
"listitem", 
"menulist", 
"menulist-button", 
"menulist-text", 
"menulist-textfield", 
"scrollbarbutton-up", 
"scrollbarbutton-down", 
"scrollbarbutton-left", 
"scrollbarbutton-right", 
"scrollbartrack-horizontal", 
"scrollbartrack-vertical", 
"scrollbarthumb-horizontal", 
"scrollbarthumb-vertical", 
"scrollbargripper-horizontal", 
"scrollbargripper-vertical", 
"slider-horizontal", 
"slider-vertical", 
"sliderthumb-horizontal", 
"sliderthumb-vertical", 
"caret", 
"searchfield", 
"searchfield-decoration", 
"searchfield-results-decoration", 
"searchfield-results-button", 
"searchfield-cancel-button", 
"textfield", 
"textarea", 
"round", 
"border", 
"content", 
"padding", 
"border-box", 
"content-box", 
"logical", 
"visual", 
"lines", 
"row", 
"row-reverse", 
"column", 
"column-reverse", 
"flex-start", 
"flex-end", 
"space-between", 
"space-around", 
"wrap", 
"wrap-reverse", 
"span", 
"min-content", 
"max-content", 
"dense", 
"to", 
    0
};
String getValueName(unsigned short id)
{
    if (id >= CSS_VAL_TOTAL || id <= 0)
        return String();
    return String(valueList[id]);
}
